apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: customer-service-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: customer-service
spec:
  hosts:
    - "*"
  gateways:
    - customer-service-gateway
  http:
    - match:
        - uri:
            exact: /customer-service
      route:
        - destination:
            host: customer-service
            port:
              number: 8080
              
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appname-deployment
spec:
  selector:
    matchLabels:
      app: appname
  template:
    metadata:
      labels:
        app: appname
    spec:
      containers:
      - name: appname
        image: gcr.io/google-containers/busybox
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

apiVersion: v1
kind: Service
metadata:
  name: dave-service
spec:
  type: ClusterIP
  selector:
    app: dave
  ports:
  - port: 3000
    targetPort: 8080

              
